homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 40.794624
  longitude: -73.9657192
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 10
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

zone: !include zones.yaml

# Show links to resources in log and frontend
#introduction:

# enable ios
ios:

# Enables the frontend
frontend:

# Enables configuration UI
config:

logger:
  default: debug
  logs:
    homeassistant.components.device_tracker.asuswrt: INFO
    roku: INFO
    homeassistant.components.websocket_api: INFO

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: littlefoot.duckdns.org:8123
  ssl_certificate: /etc/letsencrypt/live/littlefoot.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/littlefoot.duckdns.org/privkey.pem
  # use_x_forwarded_for: true
  trusted_networks:
    - 192.168.1.1

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

#zwave: 
#  usb_path: /dev/ttyUSB0

#zha_new: 
#  usb_path: /dev/ttyUSB1
#  database_path: /home/homeassistant/.homeassistant/zigbee.db

mqtt:
  broker: localhost
  username: homeassistant
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

# Text to speech
tts:
  - platform: google

google_assistant:
  project_id: !secret google_project_id
  api_key: !secret google_api_key
  expose_by_default: false
  exposed_domains:
    - switch
    - light
  entity_config:
    script.bedtime:
      expose: true
    script.bedroom_chromecast_on:
      expose: true
    script.bedroom_chromecast_off:
      expose: true
    script.theater:
      expose: true

# Cloud
cloud:

rest_command:
  assistant_relay:
    url: 'http://192.168.1.190:3000/assistant'
    method: post
    content_type: application/json
    payload: >
      {
        "command": "{{ command }}",
        "user": "glen"
      }

media_player:

media_extractor:

shell_command:
  load_roku_app: 'curl -X POST http://192.168.1.67:8060/launch/{{ app }}'
  shutdown_rubick: 'bash /home/homeassistant/shutdown-rubick.sh'

switch: !include switches.yaml

ifttt:
  key: !secret ifttt

#tuya:
#  username: glen@glentaka.com
#  password: !secret tuya_password
#  country_code: 1

# Example configuration.yaml entry
device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    protocol: ssh
    username: glen
    password: !secret router_password

group: !include groups.yaml
automation: !include_dir_list automation/
script: !include scripts.yaml
