version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi3-homeassistant:0.90.1
    volumes:
      - /home/pi/smarthome/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - letsencrypt:/config/letsencrypt:ro
    restart: unless-stopped
    depends_on:
      - postgres
      - mosquitto
      - zigbee2mqtt
    network_mode: host
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    networks:
      - mqtt
    ports:
      - "1883:1883"
    volumes:
      - /home/pi/smarthome/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /home/pi/smarthome/mosquitto/passwd:/mosquitto/config/passwd
  postgres:
    container_name: postgres
    image: postgres:9
    volumes:
      - /mnt/usb/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  duckdns:
    container_name: duckdns
    image: linuxserver/duckdns
    environment:
      - TZ=America/New_York
      - SUBDOMAINS=littlefoot
      - TOKEN=28f2c3d2-a1a8-4fe8-9b66-21c443f556b8
    restart: unless-stopped
  letsencrypt:
    container_name: letsencrypt
    image: lsioarmhf/letsencrypt
    environment:
      - TZ=America/New_York
      - URL=littlefoot.duckdns.org
      - EMAIL=glen@glentaka.com
      - VALIDATION=http
    ports:
      - "80:80"
    cap_add:
      - NET_ADMIN 
    volumes:
      - letsencrypt:/config/etc/letsencrypt
    restart: unless-stopped
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:arm32v6
    #build:
    #  context: ./zigbee2mqtt-repo
    #  dockerfile: docker/Dockerfile.arm32v6
    #  args:
    #    COMMIT: 397772bfda765d8f757313f9b3cf54b6db34b910
    networks:
      - mqtt
    volumes:
      - /home/pi/smarthome/zigbee2mqtt:/app/data
    depends_on:
      - mosquitto
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
volumes:
  letsencrypt:
networks:
  mqtt:
