version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /home/glen/smarthome/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - letsencrypt:/config/letsencrypt:ro
    restart: unless-stopped
    depends_on:
      - postgres
      - mosquitto
      - zigbee2mqtt
    network_mode: host
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1893:1883"
    networks:
      - mqtt
    volumes:
      - /home/glen/smarthome/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /home/glen/smarthome/mosquitto/passwd:/mosquitto/config/passwd
  postgres:
    container_name: postgres
    image: postgres:9
    restart: unless-stopped
    ports:
      - "5432:5432"
  duckdns:
    container_name: duckdns
    image: linuxserver/duckdns
    environment:
      - TZ=America/New_York
      - SUBDOMAINS=littlefoot
      - TOKEN=28f2c3d2-a1a8-4fe8-9b66-21c443f556b8
    restart: unless-stopped
  letsencrypt:
    container_name: letsencrypt
    image: linuxserver/letsencrypt
    environment:
      - TZ=America/Los_Angeles
      - URL=littlefoot.duckdns.org
      - EMAIL=glen@glentaka.com
      - VALIDATION=http
    ports:
      - "80:80"
    cap_add:
      - NET_ADMIN 
    volumes:
      - letsencrypt:/etc/letsencrypt
    restart: unless-stopped
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - /home/glen/smarthome/zigbee2mqtt:/app/data
    networks:
      - mqtt
    depends_on:
      - mosquitto
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: unless-stopped
  zigbee2mqttui:
    container_name: z2mui
    image: carldebilly/zigbee2mqttassistant
    ports:
      - "8800:80"
    networks:
      - mqtt
    depends_on:
      - mosquitto
      - zigbee2mqtt
    environment:
      - Z2MA_SETTINGS__MQTTSERVER=mosquitto
      - Z2MA_SETTINGS__MQTTUSERNAME=homeassistant
      - Z2MA_SETTINGS__MQTTPASSWORD=ksxiikdHHetPonVzZA3XL7u8B2X
    restart: unless-stopped
volumes:
  letsencrypt:
networks:
  mqtt:
