alias: Turn on wyze if off for 3 hours
initial_state: false
trigger:
  platform: state
  entity_id: switch.living_room_wyze
  to: 'off'
  for:
    hours: 2
action:
  service: switch.turn_on
  data:
    entity_id: group.wyze_cams
