alias: TV off
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d0001ef8506"
condition:
  condition: template
  value_template: "{{ 'double' == trigger.payload_json.click }}"
action:
  - service: script.bedroom_chromecast_off
