homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 40.794624
  longitude: -73.9657192
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 10
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

recorder:
  db_url: postgresql://postgres@postgres/homeassistant
  purge_keep_days: 3
  include:
    domains:
      - climate
      - sensor
      - binary_sensor
      - light
      - switch
      - device_tracker

zone: !include zones.yaml

# Show links to resources in log and frontend
#introduction:

# enable ios
ios:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

logger:
  default: info
  logs:
    roku: INFO
    pychromecast: INFO
    asyncssh: WARN
    homeassistant.components.device_tracker.asuswrt: WARN
    homeassistant.components.switch.command_line: WARN
    homeassistant.components.websocket_api: INFO

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.162
    token: 6b5543335866534e586c6f4239304546

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: littlefoot.duckdns.org:8123
  ssl_certificate: /config/letsencrypt/live/littlefoot.duckdns.org/fullchain.pem
  ssl_key: /config/letsencrypt/live/littlefoot.duckdns.org/privkey.pem
  # use_x_forwarded_for: true
  trusted_networks:
    - 192.168.1.1

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Input select for Zigbee2mqtt debug level
input_select:
  zigbee2mqtt_log_level:
    name: Zigbee2mqtt Log Level
    options:
     - debug
     - info
     - warn
     - error
    initial: info
    icon: mdi:format-list-bulleted

# Input boolean for enabling/disabling joining
input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless

# Timer for joining time remaining (120 sec = 2 min)
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 120

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - climate
      - sensor
      - binary_sensor
      - light
      - switch
      - device_tracker

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

sensor:
  # Weather prediction
  - platform: yr
  # Sensor for monitoring the bridge state
  - platform: mqtt
    name: Zigbee2mqtt Bridge state
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless


#zwave: 
#  usb_path: /dev/ttyUSB0

#zha_new: 
#  usb_path: /dev/ttyUSB1
#  database_path: /home/homeassistant/.homeassistant/zigbee.db

mqtt:
  broker: mosquitto
  username: homeassistant
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

# Text to speech
tts:
  - platform: google

google_assistant:
  project_id: !secret google_project_id
  api_key: !secret google_api_key
  exposed_domains:
    - light
    - climate
    - vacuum
  entity_config:
    switch.computer:
      expose: true
    script.bedtime:
      expose: true
    script.bedroom_tv_on:
      expose: true
    script.bedroom_tv_off:
      expose: true
    script.tv_on:
      expose: true
    script.tv_off:
      expose: true
    script.theater:
      expose: true
    light.0xb0ce1814030dad86_light:
      expose: false
    light.0xb0ce1814030dcd16_light:
      expose: false
    light.0xb0ce1814030dedf3_light:
      expose: false
    light.0xb0ce1814030ef600_light:
      expose: false
    light.0xb0ce18140316d859_light:
      expose: false
    light.0xb0ce1814031bbfb6_light:
      expose: false
    light.0xb0ce1814031c8686_light:
      expose: false
    light.0xb0ce1814031cdeb3_light:
      expose: false
    light.0xb0ce181403349cfc_light:
      expose: false
    light.0xb0ce18140334b0ab_light:
      expose: false
    light.0xb0ce181403364149_light:
      expose: false

# Cloud
cloud:

rest_command:
  assistant_relay:
    url: 'http://192.168.1.190:3000/assistant'
    method: post
    content_type: application/json
    payload: >
      {
        "command": "{{ command }}",
        "user": "glen"
      }

media_player:

media_extractor:

shell_command:
  load_roku_app: 'curl -X POST http://192.168.1.67:8060/launch/{{ app }}'
  shutdown_rubick: 'bash /home/homeassistant/shutdown-rubick.sh'

switch: !include switches.yaml

light:
#  - platform: switch
#    name: Christmas Lights
#    entity_id: switch.christmas_lights
  - platform: switch
    name: Dining Room Light
    entity_id: switch.dining_room_light
  - platform: switch
    name: Living Room Light
    entity_id: switch.living_room_light
  - platform: switch
    name: Glen's Lamp
    entity_id: switch.glen_s_lamp
  - platform: switch
    name: Marie's Lamp
    entity_id: switch.marie_s_lamp
  - platform: mqtt
    schema: json
    name: Bathroom Lights
    command_topic: "zigbee2mqtt/bathroom_lights/set"
    state_topic: "zigbee2mqtt/bathroom_lights/set"
    brightness: true
  - platform: mqtt
    schema: json
    name: Bedroom Lights
    command_topic: "zigbee2mqtt/bedroom_lights/set"
    state_topic: "zigbee2mqtt/bedroom_lights/set"
    brightness: true
  - platform: mqtt
    schema: json
    name: Kitchen Lights
    command_topic: "zigbee2mqtt/kitchen_lights/set"
    state_topic: "zigbee2mqtt/kitchen_lights/set"
    brightness: true
  - platform: mqtt
    schema: json
    name: Office Lights
    command_topic: "zigbee2mqtt/office_lights/set"
    state_topic: "zigbee2mqtt/office_lights/set"
    brightness: true

climate:
  - platform: generic_thermostat
    name: Living Room Thermostat
    heater: switch.living_room_ac
    ac_mode: true
    target_sensor: sensor.0x00158d00022cc96b_temperature
    min_cycle_duration:
      minutes: 10
    away_temp: 85
  - platform: generic_thermostat
    name: Bedroom Thermostat
    heater: switch.bedroom_ac
    ac_mode: true
    target_sensor: sensor.0x00158d00022c7d5b_temperature
    min_cycle_duration:
      minutes: 10
    away_temp: 85

ifttt:
  key: !secret ifttt

#tuya:
#  username: glen@glentaka.com
#  password: !secret tuya_password
#  country_code: 1

# Example configuration.yaml entry
device_tracker:
  - platform: asuswrt
 
asuswrt:
  host: 192.168.1.1
  protocol: ssh
  username: glen
  ssh_key: asuswrt.key

group: !include groups.yaml
automation: !include_dir_list automation/
script: !include scripts.yaml
