- platform: mqtt
  name: "Zigbee2mqtt Main join"
  state_topic: "zigbee2mqtt/bridge/config/permit_join"
  command_topic: "zigbee2mqtt/bridge/config/permit_join"
  payload_on: "true"
  payload_off: "false"
- platform: command_line
  switches:
    #toggles bedroom Roku TV
    bedroom_tv_power:
      command_on: 'curl -X POST http://192.168.50.67:8060/keypress/PowerOn'
      command_off: 'curl -X POST http://192.168.50.67:8060/keypress/PowerOff'
      command_state: 'curl -s GET http://192.168.50.67:8060/query/device-info | grep power-mode | sed -e "s:<power-mode>DisplayOff</power-mode>:OFF:" -e "s:<power-mode>PowerOn</power-mode>:ON:"'
      value_template: '{{ value == "ON" }}'
- platform: broadlink
  host: 192.168.50.155
  mac: '78:0F:77:18:5B:C4'
  type: rm_mini
  switches:
    samsung_tv:
      friendly_name: "Samsung TV Power"
      command_on: 'JgB2ApaUFDYUNxM3ExITEhMSExITEhM3FDcTNxMSExITEhMSExITEhM3FBITEhMSExITEhMSEzcTEhM3FDYUNxM3EzcTNxMABguXlBM3EzcTNxQSExITExITEhMSNxM3EzcTExITExITEhMTEhMSNxMTEhMSExITEhMTEhM3ExMSNxM3EzcTNxM3FDcTAAYLlpQUNxM3EzcTExITEhMSExITEzYUNxM3ExMSExISExITEhMSEzcUEhMSExITEhMSExITNxMSEzcUNhQ3EzcTNxM3EwAGC5eUEzcTNxM3ExITEhMSFBEUEhM3EzcTNxMSExITEhMSExITEhQ2FBITEhMSExITEhMSEzcTEhM3EzcUNhQ3EzcTNxMABguWlBQ3EzcTNxMTEhMSExITEhMTNxM3EzcTExITEhMSExITEhMSOBMSExITExITEhMSExI4EhMSNxM3FDcTNxM3EzcTAAYMlZQUOBI3EzcTExITEhMSExITEzYUNxM4EhMSExITEhMSExITEjgTEhMSExITExITEhMSNxMTEjcTNxM3FDcTNxM4EgAGC5aUFDgSNxM3ExMSExITEhMSExM3EzcTNxMTEhMSExITEhMSExI4EhMTEhMSExMSExITEjgSExI3EzcTNxQ3EzcTNxMABgyVlRM3EzcTNxMTEhMSExITEhMTNxM4EjgSExITEhMSExITEhMSOBITExITEhMTEhMSExI3ExMSNxM3FDcTNxM3EzgSAAYLlpUTNxM3EzgSExITEhMSExITEzcTNxM3ExMSExITEhMSExITEjgTEhMSExITExITEhMSNxMTEjgSNxQ2FDcTNxM3EwANBQAA'
      command_off: 'JgB2ApaUFDYUNxM3ExITEhMSExITEhM3FDcTNxMSExITEhMSExITEhM3FBITEhMSExITEhMSEzcTEhM3FDYUNxM3EzcTNxMABguXlBM3EzcTNxQSExITExITEhMSNxM3EzcTExITExITEhMTEhMSNxMTEhMSExITEhMTEhM3ExMSNxM3EzcTNxM3FDcTAAYLlpQUNxM3EzcTExITEhMSExITEzYUNxM3ExMSExISExITEhMSEzcUEhMSExITEhMSExITNxMSEzcUNhQ3EzcTNxM3EwAGC5eUEzcTNxM3ExITEhMSFBEUEhM3EzcTNxMSExITEhMSExITEhQ2FBITEhMSExITEhMSEzcTEhM3EzcUNhQ3EzcTNxMABguWlBQ3EzcTNxMTEhMSExITEhMTNxM3EzcTExITEhMSExITEhMSOBMSExITExITEhMSExI4EhMSNxM3FDcTNxM3EzcTAAYMlZQUOBI3EzcTExITEhMSExITEzYUNxM4EhMSExITEhMSExITEjgTEhMSExITExITEhMSNxMTEjcTNxM3FDcTNxM4EgAGC5aUFDgSNxM3ExMSExITEhMSExM3EzcTNxMTEhMSExITEhMSExI4EhMTEhMSExMSExITEjgSExI3EzcTNxQ3EzcTNxMABgyVlRM3EzcTNxMTEhMSExITEhMTNxM4EjgSExITEhMSExITEhMSOBITExITEhMTEhMSExI3ExMSNxM3FDcTNxM3EzgSAAYLlpUTNxM3EzgSExITEhMSExITEzcTNxM3ExMSExITEhMSExITEjgTEhMSExITExITEhMSNxMTEjgSNxQ2FDcTNxM3EwANBQAA'
    audioengine_power:
      friendly_name: "audioengine power"
      command_on: 'JgBgAAABKZYSFBETEhQRFBEUEhMSFBEUEjkRExI5EjkRORI5ETkRORI5ERQSExEVERQSExEVERMSFBE5EjkRORE5EjkSORE5EgAFUAABKEwRAAxxAAEoTREADHAAASlMEQANBQAAAAAAAAAA'
      command_off: 'JgBgAAABKZYSFBETEhQRFBEUEhMSFBEUEjkRExI5EjkRORI5ETkRORI5ERQSExEVERQSExEVERMSFBE5EjkRORE5EjkSORE5EgAFUAABKEwRAAxxAAEoTREADHAAASlMEQANBQAAAAAAAAAA'
    audioengine_mute:
      friendly_name: "audioengine mute"
      command_on: 'JgBoAAABKZYRFRETEhQRFBITEhQRFBEUEjkSEhI5EjkRORI5ETkRORI5ETkRFREUEhMRFRETEhQRFBEUEjkSOBE5EjkSOBE6EgAFTwABKE0SAAxvAAEpSxIADG8AASpLEgAMbwABKE0RAA0F'
      command_off: 'JgBoAAABKZYRFRETEhQRFBITEhQRFBEUEjkSEhI5EjkRORI5ETkRORI5ETkRFREUEhMRFRETEhQRFBEUEjkSOBE5EjkSOBE6EgAFTwABKE0SAAxvAAEpSxIADG8AASpLEgAMbwABKE0RAA0F'
