- platform: mqtt
  name: "Zigbee2mqtt Main join"
  state_topic: "zigbee2mqtt/bridge/config/permit_join"
  command_topic: "zigbee2mqtt/bridge/config/permit_join"
  payload_on: "true"
  payload_off: "false"
- platform: command_line
  switches:
    #toggles bedroom Roku TV
    bedroom_tv_power:
      command_on: 'curl -X POST http://192.168.1.67:8060/keypress/PowerOn'
      command_off: 'curl -X POST http://192.168.1.67:8060/keypress/PowerOff'
      command_state: 'curl -s GET http://192.168.1.67:8060/query/device-info | grep power-mode | sed -e "s:<power-mode>DisplayOff</power-mode>:OFF:" -e "s:<power-mode>PowerOn</power-mode>:ON:"'
      value_template: '{{ value == "ON" }}'
- platform: wake_on_lan
  mac_address: "E0-D5-5E-0C-D4-87"
  host: 192.168.1.98
  name: Computer
  broadcast_address: 192.168.1.255
  turn_off:
    service: shell_command.shutdown_rubick
- platform: tuya
  host: 192.168.1.104
  local_key: 5c7312a0ec1b4f28
  device_id: 50684814bcddc209a824
  switches:
    living_room_ac:
      friendly_name: Living Room AC
      id: 1
- platform: tuya
  host: 192.168.1.201
  local_key: bfb03f52d89a61a1
  device_id: 8281608184f3eb680f4f
  switches:
    bedroom_speakers:
      friendly_name: Bedroom Speakers
      id: 1
- platform: tuya
  host: 192.168.1.148
  local_key: d9641ffef5786375
  device_id: 82816081b4e62d41f660
  switches:
    marie_lamp:
      friendly_name: Marie's Lamp
      id: 1
- platform: tuya
  host: 192.168.1.31
  local_key: 163b72e0c6de356a
  device_id: 24083847bcddc28b3eea
  switches:
    glen_lamp:
      friendly_name: Glen's Lamp
      id: 1
- platform: tuya
  host: 192.168.1.176
  local_key: 0e0ed1eb24ecafb7
  device_id: 8281608184f3eb6806c4
  switches:
    dining_room_light:
      friendly_name: Dining Room Light
      id: 1
- platform: tuya
  host: 192.168.1.220
  local_key: bcb9246d38337185
  device_id: 8281608184f3eb6806f0
  switches:
    living_room_wyze:
      friendly_name: Living Room Wyze
      id: 1
- platform: tuya
  host: 192.168.1.129
  local_key: e12e0998127209a7
  device_id: 2408384784f3eb551fb2
  switches:
    bedroom_wyze:
      friendly_name: Bedroom Wyze
      id: 1
- platform: tuya
  host: 192.168.1.251
  local_key: fe75d57a47a85ca3
  device_id: 82816081b4e62d41fdc9
  switches:
    living_room_light:
      friendly_name: Living Room Light
      id: 1
- platform: tuya
  host: 192.168.1.252
  local_key: 4f62d4b5d2ff53c1
  device_id: 50684814dc4f2233de45
  switches:
    bedroom_ac:
      friendly_name: Bedroom AC
      id: 1
- platform: tuya
  host: 192.168.1.203
  local_key: e7a48105bb6bf008
  device_id: 2408384784f3eb551cd5
  switches:
    christmas_lights:
      friendly_name: Christmas Lights
      id: 1
- platform: broadlink
  host: 192.168.1.155
  mac: '78:0F:77:18:5B:C4'
  type: rm_mini
  switches:
    samsung_tv:
      friendly_name: "Samsung TV Power"
      command_on: 'JgB2ApaUFDYUNxM3ExITEhMSExITEhM3FDcTNxMSExITEhMSExITEhM3FBITEhMSExITEhMSEzcTEhM3FDYUNxM3EzcTNxMABguXlBM3EzcTNxQSExITExITEhMSNxM3EzcTExITExITEhMTEhMSNxMTEhMSExITEhMTEhM3ExMSNxM3EzcTNxM3FDcTAAYLlpQUNxM3EzcTExITEhMSExITEzYUNxM3ExMSExISExITEhMSEzcUEhMSExITEhMSExITNxMSEzcUNhQ3EzcTNxM3EwAGC5eUEzcTNxM3ExITEhMSFBEUEhM3EzcTNxMSExITEhMSExITEhQ2FBITEhMSExITEhMSEzcTEhM3EzcUNhQ3EzcTNxMABguWlBQ3EzcTNxMTEhMSExITEhMTNxM3EzcTExITEhMSExITEhMSOBMSExITExITEhMSExI4EhMSNxM3FDcTNxM3EzcTAAYMlZQUOBI3EzcTExITEhMSExITEzYUNxM4EhMSExITEhMSExITEjgTEhMSExITExITEhMSNxMTEjcTNxM3FDcTNxM4EgAGC5aUFDgSNxM3ExMSExITEhMSExM3EzcTNxMTEhMSExITEhMSExI4EhMTEhMSExMSExITEjgSExI3EzcTNxQ3EzcTNxMABgyVlRM3EzcTNxMTEhMSExITEhMTNxM4EjgSExITEhMSExITEhMSOBITExITEhMTEhMSExI3ExMSNxM3FDcTNxM3EzgSAAYLlpUTNxM3EzgSExITEhMSExITEzcTNxM3ExMSExITEhMSExITEjgTEhMSExITExITEhMSNxMTEjgSNxQ2FDcTNxM3EwANBQAA'
      command_off: 'JgB2ApaUFDYUNxM3ExITEhMSExITEhM3FDcTNxMSExITEhMSExITEhM3FBITEhMSExITEhMSEzcTEhM3FDYUNxM3EzcTNxMABguXlBM3EzcTNxQSExITExITEhMSNxM3EzcTExITExITEhMTEhMSNxMTEhMSExITEhMTEhM3ExMSNxM3EzcTNxM3FDcTAAYLlpQUNxM3EzcTExITEhMSExITEzYUNxM3ExMSExISExITEhMSEzcUEhMSExITEhMSExITNxMSEzcUNhQ3EzcTNxM3EwAGC5eUEzcTNxM3ExITEhMSFBEUEhM3EzcTNxMSExITEhMSExITEhQ2FBITEhMSExITEhMSEzcTEhM3EzcUNhQ3EzcTNxMABguWlBQ3EzcTNxMTEhMSExITEhMTNxM3EzcTExITEhMSExITEhMSOBMSExITExITEhMSExI4EhMSNxM3FDcTNxM3EzcTAAYMlZQUOBI3EzcTExITEhMSExITEzYUNxM4EhMSExITEhMSExITEjgTEhMSExITExITEhMSNxMTEjcTNxM3FDcTNxM4EgAGC5aUFDgSNxM3ExMSExITEhMSExM3EzcTNxMTEhMSExITEhMSExI4EhMTEhMSExMSExITEjgSExI3EzcTNxQ3EzcTNxMABgyVlRM3EzcTNxMTEhMSExITEhMTNxM4EjgSExITEhMSExITEhMSOBITExITEhMTEhMSExI3ExMSNxM3FDcTNxM3EzgSAAYLlpUTNxM3EzgSExITEhMSExITEzcTNxM3ExMSExITEhMSExITEjgTEhMSExITExITEhMSNxMTEjgSNxQ2FDcTNxM3EwANBQAA'
    audioengine_power:
      friendly_name: "audioengine power"
      command_on: 'JgBgAAABKZYSFBETEhQRFBEUEhMSFBEUEjkRExI5EjkRORI5ETkRORI5ERQSExEVERQSExEVERMSFBE5EjkRORE5EjkSORE5EgAFUAABKEwRAAxxAAEoTREADHAAASlMEQANBQAAAAAAAAAA'
      command_off: 'JgBgAAABKZYSFBETEhQRFBEUEhMSFBEUEjkRExI5EjkRORI5ETkRORI5ERQSExEVERQSExEVERMSFBE5EjkRORE5EjkSORE5EgAFUAABKEwRAAxxAAEoTREADHAAASlMEQANBQAAAAAAAAAA'
    audioengine_mute:
      friendly_name: "audioengine mute"
      command_on: 'JgBoAAABKZYRFRETEhQRFBITEhQRFBEUEjkSEhI5EjkRORI5ETkRORI5ETkRFREUEhMRFRETEhQRFBEUEjkSOBE5EjkSOBE6EgAFTwABKE0SAAxvAAEpSxIADG8AASpLEgAMbwABKE0RAA0F'
      command_off: 'JgBoAAABKZYRFRETEhQRFBITEhQRFBEUEjkSEhI5EjkRORI5ETkRORI5ETkRFREUEhMRFRETEhQRFBEUEjkSOBE5EjkSOBE6EgAFTwABKE0SAAxvAAEpSxIADG8AASpLEgAMbwABKE0RAA0F'
