alias: Bathroom Light Switch
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d0002133460"
condition:
  condition: template
  value_template: "{{ trigger.payload_json.click is defined }}"
action:
  service: script.automatic_light_switch
  data_template:
    entity_id: light.bathroom_lights
    click: "{{ trigger.payload_json.click }}"
