alias: Bathroom Light Switch
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d0002133460"
action:
  service: script.automatic_light_switch
  data_template:
    entity_id: group.bathroom_lights
    click: "{{ trigger.payload_json.click }}"
