alias: Bedroom Light Switch
initial_state: true
trigger:
  platform: state
  entity_id: sensor.0x00158d000238a684_click
condition:
  condition: template
  value_template: "{{ trigger.to_state.state is not none and trigger.to_state.state != 'idle' }}"
action:
  service: script.automatic_light_switch
  data_template:
    entity_id: light.bedroom_lights
    click: "{{ trigger.to_state.state }}"
