alias: Dining Room Lamp
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d0001e79023"
condition:
  condition: template
  value_template: "{{ true if trigger.payload_json.click else false }}"
action:
  service: switch.toggle
  data:
    entity_id: switch.dining_room_light
