alias: Dining Room Lamp
initial_state: true
trigger:
  platform: state
  entity_id: sensor.0x00158d0001e79023_click
condition:
  condition: template
  value_template: "{{ trigger.to_state.state == 'single' }}"
action:
  service: switch.toggle
  data:
    entity_id: switch.dining_room_light
