alias: Foyer Light Switch
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d000213339e"
condition:
  condition: template
  value_template: '{{ "both" == trigger.payload_json.click }}'
action:
  service: script.automatic_light_switch
  data:
    entity_id: light.0xb0ce18140310d9f8_light
    click: 'left'
