alias: Foyer Light Switch
initial_state: true
trigger:
  platform: state
  entity_id: sensor.0x00158d000213339e_click
condition:
  condition: template
  value_template: "{{ trigger.to_state.state == 'both' }}"
action:
  service: script.automatic_light_switch
  data:
    entity_id: light.0xb0ce18140310d9f8_light
    click: 'left'
