alias: Foyer light
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.0x00158d00022eff01_contact
  to: 'on'
action:
  - service: light.turn_on
    data:
      entity_id: light.0xb0ce18140310d9f8_light
      brightness: 255
  - delay:
      minutes: 1
  - service: light.turn_off
    data:
      entity_id: light.0xb0ce18140310d9f8_light
