alias: Hall Light Switch
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d000238a63d"
condition:
  condition: template
  value_template: "{{ true if trigger.payload_json.click else false }}"
action:
  service: script.automatic_light_switch
  data_template:
    entity_id: group.hall_lights
    click: "{{ trigger.payload_json.click }}"
