alias: Kitchen Light Switch
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d000213339e"
condition:
  condition: template
  value_template: "{{ trigger.payload_json.click is not none }}"
action:
  service: script.automatic_light_switch
  data_template:
    entity_id: light.kitchen_lights
    click: "{{ trigger.payload_json.click }}
