alias: Kitchen Light Switch
initial_state: true
trigger:
  platform: state
  entity_id: sensor.0x00158d000213339e_click
condition:
  condition: template
  value_template: "{{ trigger.to_state.state is not none }}"
action:
  service: script.automatic_light_switch
  data_template:
    entity_id: light.kitchen_lights
    click: "{{ trigger.to_state.state }}"
