alias: Living Room Lamp
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d0001e88eae"
condition:
  condition: template
  value_template: "{{ trigger.payload_json.click }}"
action:
  service: switch.toggle
  data:
    entity_id: switch.living_room_light
