alias: Office dimmer
initial_state: true
trigger:
  platform: state
  entity_id: sensor.0x000b57fffe90228b_brightness
action:
  service: script.dimmer_light
  data_template:
    entity_id: group.office_lights
    brightness: "{{ trigger.to_state.state }}"
