alias: Turn on Bedroom Thermostat
initial_state: true
trigger:
  - platform: state
    entity_id:
      - group.living_room_windows
      - binary_sensor.0x00158d00022bd487
      - group.bedroom_windows
      - binary_sensor.0x00158d000237c71b
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.bedroom_windows
      state: 'off'
    - condition: state
      entity_id: climate.bedroom_thermostat
      state: 'off'
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: group.living_room_windows
              state: 'off'
            - condition: state
              entity_id: binary_sensor.0x00158d00022bd487
              state: 'off'
        - condition: state
          entity_id: binary_sensor.0x00158d000237c71b
          state: 'off'
action:
  service: climate.turn_on
  data:
    entity_id: climate.bedroom_thermostat
