alias: Turn off Bedroom AC
initial_state: true
trigger:
  - platform: state
    entity_id:
      - sensor.0x00158d00022cc96b_temperature
      - sensor.0x00158d00022c7d5b_temperature
      - group.living_room_windows
      - binary_sensor.0x00158d00022bd487
      - group.bedroom_windows
      - binary_sensor.0x00158d000237c71b
      - group.phones
      - sun.sun
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: switch.bedroom_ac
      state: 'on'
    - condition: or
      conditions:
        # open doors/windows
        - condition: or
          conditions:
            - condition: state
              entity_id: group.bedroom_windows
              state: 'on'
            - condition: and
              conditions:
                - condition: or
                  conditions:
                    - condition: state
                      entity_id: group.living_room_windows
                      state: 'on'
                    - condition: state
                      entity_id: binary_sensor.0x00158d00022bd487
                      state: 'on'
                      for:
                        seconds: 30
                - condition: state
                  entity_id: binary_sensor.0x00158d000237c71b
                  state: 'on'
        # nobody home
        - condition: and
          conditions:
            - condition: numeric_state
              entity_id: sensor.0x00158d00022c7d5b_temperature
              below: 85
            - condition: state
              entity_id: group.phones
              state: 'not_home'
        # home and day
        - condition: and
          conditions:
            - condition: numeric_state
              entity_id: sensor.0x00158d00022c7d5b_temperature
              below: 76
            - condition: state
              entity_id: group.phones
              state: 'home'
            - condition: time
              after: '8:00'
              before: '23:00'
        # home and night
        - condition: and
          conditions:
            - condition: numeric_state
              entity_id: sensor.0x00158d00022c7d5b_temperature
              below: 77
            - condition: state
              entity_id: group.phones
              state: 'home'
            - condition: time
              after: '23:00'
              before: '8:00'
action:
  service: switch.turn_off
  data:
    entity_id: switch.bedroom_ac
