alias: Turn off Dining Room AC
initial_state: true
trigger:
  - platform: state
    entity_id:
      - sensor.0x00158d00022cc96b_temperature
      - sensor.0x00158d00022c7d5b_temperature
      - group.living_room_windows
      - group.bedroom_windows
      - binary_sensor.0x00158d000237c71b
      - group.phones
condition:
  condition: or
  conditions:
    # open doors/windows
    - condition: or
      conditions:
        - condition: state
          entity_id: group.living_room_windows
          state: 'on'
        - condition: and
          conditions:
            - condition: state
              entity_id: group.bedroom_windows
              state: 'on'
            - condition: state
              entity_id: binary_sensor.0x00158d000237c71b
              state: 'on'
    # nobody home
    - condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.0x00158d00022cc96b_temperature
          below: 85
        - condition: state
          entity_id: group.phones
          state: 'not_home'
    # home and day
    - condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.0x00158d00022cc96b_temperature
          below: 77
        - condition: state
          entity_id: group.phones
          state: 'home'
        - condition: state
          entity_id: sun.sun
          state: 'above_horizon'
    # home and night
    - condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.0x00158d00022cc96b_temperature
          below: 78
        - condition: state
          entity_id: group.phones
          state: 'home'
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
action:
  service: switch.turn_off
  data:
    entity_id: switch.50684814bcddc209a824
