alias: Turn off Bedroom Thermostat
initial_state: true
trigger:
  - platform: state
    entity_id:
      - group.living_room_windows
      - binary_sensor.0x00158d00022bd487_contact
      - group.bedroom_windows
      - binary_sensor.0x00158d000237c71b_contact
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: group.bedroom_windows
      state: 'on'
    - condition: and
      conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: group.living_room_windows
              state: 'on'
            - condition: state
              entity_id: binary_sensor.0x00158d00022bd487_contact
              state: 'on'
              for:
                seconds: 30
        - condition: state
          entity_id: binary_sensor.0x00158d000237c71b_contact
          state: 'on'
action:
  - service: climate.turn_off
    data:
      entity_id: climate.bedroom_thermostat
  - service: switch.turn_off
    data:
      entity_id: switch.bedroom_ac
