alias: light 2
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d000278eb90"
condition:
  condition: template
  value_template: "{{ 'rotate_left' == trigger.payload_json.action }}"
action:
  service: light.toggle
  data:
    entity_id: light.0xb0ce1814030ef600
