alias: Bedroom Ikea
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x000b57fffeaa3920"
condition:
  condition: template
  value_template: "{{ trigger.payload_json.action is defined }}"
action:
  service: script.bedroom_ikea_button
  data_template:
    click: "{{ trigger.payload_json.action }}"
