alias: Glen button
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d0001e89324"
condition:
  condition: template
  value_template: "{{ true if trigger.payload_json.click else false }}"
action:
  service: script.bedroom_button
  data_template:
    lamp_entity_id: light.glen_s_lamp
    click: "{{ trigger.payload_json.click }}"

