alias: Glen button
initial_state: true
trigger:
  platform: state
  entity_id: sensor.0x00158d0001e89324_click
condition:
  condition: template
  value_template: "{{ trigger.to_state.state is not none }}"
action:
  service: script.bedroom_button
  data_template:
    lamp_entity_id: light.glen_s_lamp
    click: "{{ trigger.to_state.state }}"

