alias: Ikea
initial_state: true
trigger:
  platform: state
  entity_id: sensor.0x000b57fffeb127f8_action
condition:
  condition: template
  value_template: "{{ trigger.to_state.state is not none }}"
action:
  service: script.ikea_button
  data_template:
    entity_id: light.office_lights
    click: "{{ trigger.to_state.state }}"

