alias: Ikea
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x000b57fffeb127f8"
condition:
  condition: template
  value_template: "{{ trigger.payload_json.action is not none }}"
action:
  service: script.ikea_button
  data_template:
    entity_id: light.office_lights
    click: "{{ trigger.payload_json.action }}

