alias: Marie button
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d0001ef8506"
condition:
  condition: template
  value_template: "{{ trigger.payload_json.click is not none }}"
action:
  service: script.bedroom_button
  data_template:
    lamp_entity_id: light.marie_s_lamp
    click: "{{ trigger.payload_json.click }}"

