alias: TV button
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d0001ef8506"
condition:
  condition: template
  value_template: "{{ trigger.payload_json.click is defined }}"
action:
  service_template: >
    {% set click = trigger.payload_json.click %}
    {% if click == 'single' %}
      script.tv_toggle
    {% elif click == 'double' %}
      script.bedtime
    {% endif %}

