alias: Turn Off Bedroom Lights #2
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d0001ef8506"
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ 'quadruple' == trigger.payload_json.click }}"
    - condition: state
      entity_id: group.bedroom_lights
      state: 'on'
action:
  service: light.turn_off
  data:
    entity_id: group.bedroom_lights
