alias: Turn on Bedroom Lights during day #2
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d0001ef8506"
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ 'quadruple' == trigger.payload_json.click }}"
    - condition: state
      entity_id: group.bedroom_lights
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
action:
  service: light.turn_on
  data:
    entity_id: group.bedroom_lights
    brightness_pct: 100
