alias: Toggle Bedroom Lights
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d0001ef8506"
condition:
  condition: template
  value_template: "{{ 'quadruple' == trigger.payload_json.click }}"
action:
  - service: script.automatic_light_toggle
    data:
      entity_id: group.bedroom_lights
