alias: Toggle Marie Lamp
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d0001ef8506"
condition:
  condition: template
  value_template: "{{ 'triple' == trigger.payload_json.click }}"
action:
  - service: switch.toggle
    entity_id: switch.maries_lamp
