alias: 50% Bathroom Lights
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d0001e89324"
condition:
  condition: template
  value_template: "{{ 'double' == trigger.payload_json.click }}"
action:
  service: light.turn_on
  data:
    entity_id: group.bathroom_lights
    brightness_pct: 50
