alias: Turn on Bathroom Lights during day
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d0001e89324"
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ 'single' == trigger.payload_json.click }}"
    - condition: state
      entity_id: group.bathroom_lights
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
action:
  service: light.turn_on
  data:
    entity_id: group.bathroom_lights
    brightness_pct: 100
