alias: Kitchen Light Switch
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d000213339e"
action:
  service: script.automatic_light_switch
  data_template:
    entity_id: group.kitchen_lights
    click: "{{ trigger.payload_json.click }}"
