alias: 1% Bedroom Lights
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d0001e79023"
condition:
  condition: template
  value_template: "{{ 'quadruple' == trigger.payload_json.click }}"
action:
  - service: light.turn_on
    data:
      entity_id: group.bedroom_lights
      brightness: 1
