alias: Turn on Bedroom Lights at night
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d0001e79023"
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ 'single' == trigger.payload_json.click }}"
    - condition: state
      entity_id: group.bedroom_lights
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: time
      after: '23:00'
      before: '6:00'
action:
  service: light.turn_on
  data:
    entity_id: group.bedroom_lights
    brightness: 1
