alias: Toggle Bedroom Lights
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d0001e79023"
condition:
  condition: template
  value_template: "{{ 'single' == trigger.payload_json.click }}"
action:
  service: light.toggle
  data:
    entity_id: group.bedroom_lights
