alias: Ducky volume
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x000b57fffe90228b"
action:
  service: media_player.volume_set
  data_template:
    entity_id: media_player.chromecast0856
    volume_level: "{{ trigger.payload_json.brightness / 255 }}"
