alias: Lamps
initial_state: false
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d00021334a8"
condition:
  condition: template
  value_template: "{{ trigger.payload_json.click != 'both' }}"
action:
  service: switch.toggle
  data_template:
    entity_id: >
      {% if trigger.payload_json.click == 'right' %}
        switch.living_room_light
      {% elif trigger.payload_json.click == 'left' %}
        switch.dining_room_light
      {% endif %}
