alias: Party
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/0x00158d00021334a8"
condition:
  condition: template
  value_template: "{{ trigger.payload_json.click == 'both' }}"
action:
  - service: rest_command.assistant_relay
    data:
      command: "play discover weekly on spotify on home group"
