alias: Turn off lights when nobody is home
initial_state: true
trigger:
  platform: state
  entity_id: group.phones
  from: 'home'
  to: 'not_home'
action:
  - service: homeassistant.turn_off
    entity_id: group.all_lights
  - service: switch.turn_off
    entity_id: group.switch_lights
